### ISSUE TITLE
Add support for Laravel 9

### ISSUE THREAD

**Issue by sawirricardo** [traincase/laravel-pdf-tinker#10]
Currently it will throw out error

**Comment by jelleroorda** [comment]
I’ll have a look at it later today

**Comment by jelleroorda** [comment]
Should be fixed:
https://github.com/traincase/laravel-pdf-tinker/releases/tag/2.0.0

When following the installation instructions it should automatically grab v2 for you when trying to install in a Laravel 9 project.

**Comment by sawirricardo** [comment]
Thank you @jelleroorda 👍
